string data_field_01  # Robot description
string data_field_02  # Serial number
string data_field_03  # IP address
string data_field_04  # Firmware version
string data_field_05  # Maximum payload
string data_field_06  # Hydraulic oil temperature
string data_field_07  # Hydraulic oil tank fill level
string data_field_08  # Hydraulic oil pressure
string data_field_09  # Reserved for future use
string data_field_10  # Reserved for future use
